/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradingRouteImport } from './routes/trading'
import { Route as GridRouteImport } from './routes/grid'
import { Route as ForecastingRouteImport } from './routes/forecasting'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AnomaliesRouteImport } from './routes/anomalies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GridIndexRouteImport } from './routes/grid/index'
import { Route as TradingPositionsRouteImport } from './routes/trading/positions'
import { Route as TradingOrdersRouteImport } from './routes/trading/orders'
import { Route as TradingNewOrderRouteImport } from './routes/trading/new-order'
import { Route as GridSectorIdRouteImport } from './routes/grid/$sectorId'
import { Route as ForecastingWindRouteImport } from './routes/forecasting/wind'
import { Route as ForecastingSolarRouteImport } from './routes/forecasting/solar'
import { Route as ForecastingPriceRouteImport } from './routes/forecasting/price'
import { Route as ForecastingDemandRouteImport } from './routes/forecasting/demand'
import { Route as DispatchNewRouteImport } from './routes/dispatch/new'
import { Route as DispatchHistoryRouteImport } from './routes/dispatch/history'
import { Route as DispatchActiveRouteImport } from './routes/dispatch/active'
import { Route as DispatchPlanIdRouteImport } from './routes/dispatch/$planId'
import { Route as AssetsWorkOrdersRouteImport } from './routes/assets/work-orders'
import { Route as AssetsHealthRouteImport } from './routes/assets/health'
import { Route as AnomaliesResolvedRouteImport } from './routes/anomalies/resolved'
import { Route as AnomaliesAllRouteImport } from './routes/anomalies/all'
import { Route as AnomaliesActiveRouteImport } from './routes/anomalies/active'
import { Route as AssetsInventoryIndexRouteImport } from './routes/assets/inventory/index'
import { Route as AssetsInventoryAssetIdRouteImport } from './routes/assets/inventory/$assetId'

const TradingRoute = TradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => rootRouteImport,
} as any)
const GridRoute = GridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastingRoute = ForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomaliesRoute = AnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GridIndexRoute = GridIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GridRoute,
} as any)
const TradingPositionsRoute = TradingPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => TradingRoute,
} as any)
const TradingOrdersRoute = TradingOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => TradingRoute,
} as any)
const TradingNewOrderRoute = TradingNewOrderRouteImport.update({
  id: '/new-order',
  path: '/new-order',
  getParentRoute: () => TradingRoute,
} as any)
const GridSectorIdRoute = GridSectorIdRouteImport.update({
  id: '/$sectorId',
  path: '/$sectorId',
  getParentRoute: () => GridRoute,
} as any)
const ForecastingWindRoute = ForecastingWindRouteImport.update({
  id: '/wind',
  path: '/wind',
  getParentRoute: () => ForecastingRoute,
} as any)
const ForecastingSolarRoute = ForecastingSolarRouteImport.update({
  id: '/solar',
  path: '/solar',
  getParentRoute: () => ForecastingRoute,
} as any)
const ForecastingPriceRoute = ForecastingPriceRouteImport.update({
  id: '/price',
  path: '/price',
  getParentRoute: () => ForecastingRoute,
} as any)
const ForecastingDemandRoute = ForecastingDemandRouteImport.update({
  id: '/demand',
  path: '/demand',
  getParentRoute: () => ForecastingRoute,
} as any)
const DispatchNewRoute = DispatchNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DispatchRoute,
} as any)
const DispatchHistoryRoute = DispatchHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DispatchRoute,
} as any)
const DispatchActiveRoute = DispatchActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => DispatchRoute,
} as any)
const DispatchPlanIdRoute = DispatchPlanIdRouteImport.update({
  id: '/$planId',
  path: '/$planId',
  getParentRoute: () => DispatchRoute,
} as any)
const AssetsWorkOrdersRoute = AssetsWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsHealthRoute = AssetsHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AssetsRoute,
} as any)
const AnomaliesResolvedRoute = AnomaliesResolvedRouteImport.update({
  id: '/resolved',
  path: '/resolved',
  getParentRoute: () => AnomaliesRoute,
} as any)
const AnomaliesAllRoute = AnomaliesAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AnomaliesRoute,
} as any)
const AnomaliesActiveRoute = AnomaliesActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => AnomaliesRoute,
} as any)
const AssetsInventoryIndexRoute = AssetsInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsInventoryAssetIdRoute = AssetsInventoryAssetIdRouteImport.update({
  id: '/inventory/$assetId',
  path: '/inventory/$assetId',
  getParentRoute: () => AssetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anomalies': typeof AnomaliesRouteWithChildren
  '/assets': typeof AssetsRouteWithChildren
  '/dispatch': typeof DispatchRouteWithChildren
  '/forecasting': typeof ForecastingRouteWithChildren
  '/grid': typeof GridRouteWithChildren
  '/trading': typeof TradingRouteWithChildren
  '/anomalies/active': typeof AnomaliesActiveRoute
  '/anomalies/all': typeof AnomaliesAllRoute
  '/anomalies/resolved': typeof AnomaliesResolvedRoute
  '/assets/health': typeof AssetsHealthRoute
  '/assets/work-orders': typeof AssetsWorkOrdersRoute
  '/dispatch/$planId': typeof DispatchPlanIdRoute
  '/dispatch/active': typeof DispatchActiveRoute
  '/dispatch/history': typeof DispatchHistoryRoute
  '/dispatch/new': typeof DispatchNewRoute
  '/forecasting/demand': typeof ForecastingDemandRoute
  '/forecasting/price': typeof ForecastingPriceRoute
  '/forecasting/solar': typeof ForecastingSolarRoute
  '/forecasting/wind': typeof ForecastingWindRoute
  '/grid/$sectorId': typeof GridSectorIdRoute
  '/trading/new-order': typeof TradingNewOrderRoute
  '/trading/orders': typeof TradingOrdersRoute
  '/trading/positions': typeof TradingPositionsRoute
  '/grid/': typeof GridIndexRoute
  '/assets/inventory/$assetId': typeof AssetsInventoryAssetIdRoute
  '/assets/inventory/': typeof AssetsInventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anomalies': typeof AnomaliesRouteWithChildren
  '/assets': typeof AssetsRouteWithChildren
  '/dispatch': typeof DispatchRouteWithChildren
  '/forecasting': typeof ForecastingRouteWithChildren
  '/trading': typeof TradingRouteWithChildren
  '/anomalies/active': typeof AnomaliesActiveRoute
  '/anomalies/all': typeof AnomaliesAllRoute
  '/anomalies/resolved': typeof AnomaliesResolvedRoute
  '/assets/health': typeof AssetsHealthRoute
  '/assets/work-orders': typeof AssetsWorkOrdersRoute
  '/dispatch/$planId': typeof DispatchPlanIdRoute
  '/dispatch/active': typeof DispatchActiveRoute
  '/dispatch/history': typeof DispatchHistoryRoute
  '/dispatch/new': typeof DispatchNewRoute
  '/forecasting/demand': typeof ForecastingDemandRoute
  '/forecasting/price': typeof ForecastingPriceRoute
  '/forecasting/solar': typeof ForecastingSolarRoute
  '/forecasting/wind': typeof ForecastingWindRoute
  '/grid/$sectorId': typeof GridSectorIdRoute
  '/trading/new-order': typeof TradingNewOrderRoute
  '/trading/orders': typeof TradingOrdersRoute
  '/trading/positions': typeof TradingPositionsRoute
  '/grid': typeof GridIndexRoute
  '/assets/inventory/$assetId': typeof AssetsInventoryAssetIdRoute
  '/assets/inventory': typeof AssetsInventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anomalies': typeof AnomaliesRouteWithChildren
  '/assets': typeof AssetsRouteWithChildren
  '/dispatch': typeof DispatchRouteWithChildren
  '/forecasting': typeof ForecastingRouteWithChildren
  '/grid': typeof GridRouteWithChildren
  '/trading': typeof TradingRouteWithChildren
  '/anomalies/active': typeof AnomaliesActiveRoute
  '/anomalies/all': typeof AnomaliesAllRoute
  '/anomalies/resolved': typeof AnomaliesResolvedRoute
  '/assets/health': typeof AssetsHealthRoute
  '/assets/work-orders': typeof AssetsWorkOrdersRoute
  '/dispatch/$planId': typeof DispatchPlanIdRoute
  '/dispatch/active': typeof DispatchActiveRoute
  '/dispatch/history': typeof DispatchHistoryRoute
  '/dispatch/new': typeof DispatchNewRoute
  '/forecasting/demand': typeof ForecastingDemandRoute
  '/forecasting/price': typeof ForecastingPriceRoute
  '/forecasting/solar': typeof ForecastingSolarRoute
  '/forecasting/wind': typeof ForecastingWindRoute
  '/grid/$sectorId': typeof GridSectorIdRoute
  '/trading/new-order': typeof TradingNewOrderRoute
  '/trading/orders': typeof TradingOrdersRoute
  '/trading/positions': typeof TradingPositionsRoute
  '/grid/': typeof GridIndexRoute
  '/assets/inventory/$assetId': typeof AssetsInventoryAssetIdRoute
  '/assets/inventory/': typeof AssetsInventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anomalies'
    | '/assets'
    | '/dispatch'
    | '/forecasting'
    | '/grid'
    | '/trading'
    | '/anomalies/active'
    | '/anomalies/all'
    | '/anomalies/resolved'
    | '/assets/health'
    | '/assets/work-orders'
    | '/dispatch/$planId'
    | '/dispatch/active'
    | '/dispatch/history'
    | '/dispatch/new'
    | '/forecasting/demand'
    | '/forecasting/price'
    | '/forecasting/solar'
    | '/forecasting/wind'
    | '/grid/$sectorId'
    | '/trading/new-order'
    | '/trading/orders'
    | '/trading/positions'
    | '/grid/'
    | '/assets/inventory/$assetId'
    | '/assets/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anomalies'
    | '/assets'
    | '/dispatch'
    | '/forecasting'
    | '/trading'
    | '/anomalies/active'
    | '/anomalies/all'
    | '/anomalies/resolved'
    | '/assets/health'
    | '/assets/work-orders'
    | '/dispatch/$planId'
    | '/dispatch/active'
    | '/dispatch/history'
    | '/dispatch/new'
    | '/forecasting/demand'
    | '/forecasting/price'
    | '/forecasting/solar'
    | '/forecasting/wind'
    | '/grid/$sectorId'
    | '/trading/new-order'
    | '/trading/orders'
    | '/trading/positions'
    | '/grid'
    | '/assets/inventory/$assetId'
    | '/assets/inventory'
  id:
    | '__root__'
    | '/'
    | '/anomalies'
    | '/assets'
    | '/dispatch'
    | '/forecasting'
    | '/grid'
    | '/trading'
    | '/anomalies/active'
    | '/anomalies/all'
    | '/anomalies/resolved'
    | '/assets/health'
    | '/assets/work-orders'
    | '/dispatch/$planId'
    | '/dispatch/active'
    | '/dispatch/history'
    | '/dispatch/new'
    | '/forecasting/demand'
    | '/forecasting/price'
    | '/forecasting/solar'
    | '/forecasting/wind'
    | '/grid/$sectorId'
    | '/trading/new-order'
    | '/trading/orders'
    | '/trading/positions'
    | '/grid/'
    | '/assets/inventory/$assetId'
    | '/assets/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnomaliesRoute: typeof AnomaliesRouteWithChildren
  AssetsRoute: typeof AssetsRouteWithChildren
  DispatchRoute: typeof DispatchRouteWithChildren
  ForecastingRoute: typeof ForecastingRouteWithChildren
  GridRoute: typeof GridRouteWithChildren
  TradingRoute: typeof TradingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trading': {
      id: '/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof TradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid': {
      id: '/grid'
      path: '/grid'
      fullPath: '/grid'
      preLoaderRoute: typeof GridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasting': {
      id: '/forecasting'
      path: '/forecasting'
      fullPath: '/forecasting'
      preLoaderRoute: typeof ForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomalies': {
      id: '/anomalies'
      path: '/anomalies'
      fullPath: '/anomalies'
      preLoaderRoute: typeof AnomaliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid/': {
      id: '/grid/'
      path: '/'
      fullPath: '/grid/'
      preLoaderRoute: typeof GridIndexRouteImport
      parentRoute: typeof GridRoute
    }
    '/trading/positions': {
      id: '/trading/positions'
      path: '/positions'
      fullPath: '/trading/positions'
      preLoaderRoute: typeof TradingPositionsRouteImport
      parentRoute: typeof TradingRoute
    }
    '/trading/orders': {
      id: '/trading/orders'
      path: '/orders'
      fullPath: '/trading/orders'
      preLoaderRoute: typeof TradingOrdersRouteImport
      parentRoute: typeof TradingRoute
    }
    '/trading/new-order': {
      id: '/trading/new-order'
      path: '/new-order'
      fullPath: '/trading/new-order'
      preLoaderRoute: typeof TradingNewOrderRouteImport
      parentRoute: typeof TradingRoute
    }
    '/grid/$sectorId': {
      id: '/grid/$sectorId'
      path: '/$sectorId'
      fullPath: '/grid/$sectorId'
      preLoaderRoute: typeof GridSectorIdRouteImport
      parentRoute: typeof GridRoute
    }
    '/forecasting/wind': {
      id: '/forecasting/wind'
      path: '/wind'
      fullPath: '/forecasting/wind'
      preLoaderRoute: typeof ForecastingWindRouteImport
      parentRoute: typeof ForecastingRoute
    }
    '/forecasting/solar': {
      id: '/forecasting/solar'
      path: '/solar'
      fullPath: '/forecasting/solar'
      preLoaderRoute: typeof ForecastingSolarRouteImport
      parentRoute: typeof ForecastingRoute
    }
    '/forecasting/price': {
      id: '/forecasting/price'
      path: '/price'
      fullPath: '/forecasting/price'
      preLoaderRoute: typeof ForecastingPriceRouteImport
      parentRoute: typeof ForecastingRoute
    }
    '/forecasting/demand': {
      id: '/forecasting/demand'
      path: '/demand'
      fullPath: '/forecasting/demand'
      preLoaderRoute: typeof ForecastingDemandRouteImport
      parentRoute: typeof ForecastingRoute
    }
    '/dispatch/new': {
      id: '/dispatch/new'
      path: '/new'
      fullPath: '/dispatch/new'
      preLoaderRoute: typeof DispatchNewRouteImport
      parentRoute: typeof DispatchRoute
    }
    '/dispatch/history': {
      id: '/dispatch/history'
      path: '/history'
      fullPath: '/dispatch/history'
      preLoaderRoute: typeof DispatchHistoryRouteImport
      parentRoute: typeof DispatchRoute
    }
    '/dispatch/active': {
      id: '/dispatch/active'
      path: '/active'
      fullPath: '/dispatch/active'
      preLoaderRoute: typeof DispatchActiveRouteImport
      parentRoute: typeof DispatchRoute
    }
    '/dispatch/$planId': {
      id: '/dispatch/$planId'
      path: '/$planId'
      fullPath: '/dispatch/$planId'
      preLoaderRoute: typeof DispatchPlanIdRouteImport
      parentRoute: typeof DispatchRoute
    }
    '/assets/work-orders': {
      id: '/assets/work-orders'
      path: '/work-orders'
      fullPath: '/assets/work-orders'
      preLoaderRoute: typeof AssetsWorkOrdersRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/health': {
      id: '/assets/health'
      path: '/health'
      fullPath: '/assets/health'
      preLoaderRoute: typeof AssetsHealthRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/anomalies/resolved': {
      id: '/anomalies/resolved'
      path: '/resolved'
      fullPath: '/anomalies/resolved'
      preLoaderRoute: typeof AnomaliesResolvedRouteImport
      parentRoute: typeof AnomaliesRoute
    }
    '/anomalies/all': {
      id: '/anomalies/all'
      path: '/all'
      fullPath: '/anomalies/all'
      preLoaderRoute: typeof AnomaliesAllRouteImport
      parentRoute: typeof AnomaliesRoute
    }
    '/anomalies/active': {
      id: '/anomalies/active'
      path: '/active'
      fullPath: '/anomalies/active'
      preLoaderRoute: typeof AnomaliesActiveRouteImport
      parentRoute: typeof AnomaliesRoute
    }
    '/assets/inventory/': {
      id: '/assets/inventory/'
      path: '/inventory'
      fullPath: '/assets/inventory/'
      preLoaderRoute: typeof AssetsInventoryIndexRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/inventory/$assetId': {
      id: '/assets/inventory/$assetId'
      path: '/inventory/$assetId'
      fullPath: '/assets/inventory/$assetId'
      preLoaderRoute: typeof AssetsInventoryAssetIdRouteImport
      parentRoute: typeof AssetsRoute
    }
  }
}

interface AnomaliesRouteChildren {
  AnomaliesActiveRoute: typeof AnomaliesActiveRoute
  AnomaliesAllRoute: typeof AnomaliesAllRoute
  AnomaliesResolvedRoute: typeof AnomaliesResolvedRoute
}

const AnomaliesRouteChildren: AnomaliesRouteChildren = {
  AnomaliesActiveRoute: AnomaliesActiveRoute,
  AnomaliesAllRoute: AnomaliesAllRoute,
  AnomaliesResolvedRoute: AnomaliesResolvedRoute,
}

const AnomaliesRouteWithChildren = AnomaliesRoute._addFileChildren(
  AnomaliesRouteChildren,
)

interface AssetsRouteChildren {
  AssetsHealthRoute: typeof AssetsHealthRoute
  AssetsWorkOrdersRoute: typeof AssetsWorkOrdersRoute
  AssetsInventoryAssetIdRoute: typeof AssetsInventoryAssetIdRoute
  AssetsInventoryIndexRoute: typeof AssetsInventoryIndexRoute
}

const AssetsRouteChildren: AssetsRouteChildren = {
  AssetsHealthRoute: AssetsHealthRoute,
  AssetsWorkOrdersRoute: AssetsWorkOrdersRoute,
  AssetsInventoryAssetIdRoute: AssetsInventoryAssetIdRoute,
  AssetsInventoryIndexRoute: AssetsInventoryIndexRoute,
}

const AssetsRouteWithChildren =
  AssetsRoute._addFileChildren(AssetsRouteChildren)

interface DispatchRouteChildren {
  DispatchPlanIdRoute: typeof DispatchPlanIdRoute
  DispatchActiveRoute: typeof DispatchActiveRoute
  DispatchHistoryRoute: typeof DispatchHistoryRoute
  DispatchNewRoute: typeof DispatchNewRoute
}

const DispatchRouteChildren: DispatchRouteChildren = {
  DispatchPlanIdRoute: DispatchPlanIdRoute,
  DispatchActiveRoute: DispatchActiveRoute,
  DispatchHistoryRoute: DispatchHistoryRoute,
  DispatchNewRoute: DispatchNewRoute,
}

const DispatchRouteWithChildren = DispatchRoute._addFileChildren(
  DispatchRouteChildren,
)

interface ForecastingRouteChildren {
  ForecastingDemandRoute: typeof ForecastingDemandRoute
  ForecastingPriceRoute: typeof ForecastingPriceRoute
  ForecastingSolarRoute: typeof ForecastingSolarRoute
  ForecastingWindRoute: typeof ForecastingWindRoute
}

const ForecastingRouteChildren: ForecastingRouteChildren = {
  ForecastingDemandRoute: ForecastingDemandRoute,
  ForecastingPriceRoute: ForecastingPriceRoute,
  ForecastingSolarRoute: ForecastingSolarRoute,
  ForecastingWindRoute: ForecastingWindRoute,
}

const ForecastingRouteWithChildren = ForecastingRoute._addFileChildren(
  ForecastingRouteChildren,
)

interface GridRouteChildren {
  GridSectorIdRoute: typeof GridSectorIdRoute
  GridIndexRoute: typeof GridIndexRoute
}

const GridRouteChildren: GridRouteChildren = {
  GridSectorIdRoute: GridSectorIdRoute,
  GridIndexRoute: GridIndexRoute,
}

const GridRouteWithChildren = GridRoute._addFileChildren(GridRouteChildren)

interface TradingRouteChildren {
  TradingNewOrderRoute: typeof TradingNewOrderRoute
  TradingOrdersRoute: typeof TradingOrdersRoute
  TradingPositionsRoute: typeof TradingPositionsRoute
}

const TradingRouteChildren: TradingRouteChildren = {
  TradingNewOrderRoute: TradingNewOrderRoute,
  TradingOrdersRoute: TradingOrdersRoute,
  TradingPositionsRoute: TradingPositionsRoute,
}

const TradingRouteWithChildren =
  TradingRoute._addFileChildren(TradingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnomaliesRoute: AnomaliesRouteWithChildren,
  AssetsRoute: AssetsRouteWithChildren,
  DispatchRoute: DispatchRouteWithChildren,
  ForecastingRoute: ForecastingRouteWithChildren,
  GridRoute: GridRouteWithChildren,
  TradingRoute: TradingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
